// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_LayerGraphicsMZ","status":true,"description":"(v.1.3) Create graphic layers for parallax mapping, fog, etc. View documentation for plugin commands.","parameters":{"fixPosition":"true"}},
{"name":"BalloonSound","status":true,"description":"Associate a sound with a balloon icon.","parameters":{"iconSoundList":"[\"{\\\"balloonId\\\":\\\"1\\\",\\\"sound\\\":\\\"Miss\\\",\\\"volume\\\":\\\"30\\\",\\\"pitch\\\":\\\"100\\\",\\\"pan\\\":\\\"0\\\"}\",\"{\\\"balloonId\\\":\\\"7\\\",\\\"sound\\\":\\\"Paralyze3\\\",\\\"volume\\\":\\\"30\\\",\\\"pitch\\\":\\\"100\\\",\\\"pan\\\":\\\"0\\\"}\",\"{\\\"balloonId\\\":\\\"2\\\",\\\"sound\\\":\\\"Jump1\\\",\\\"volume\\\":\\\"30\\\",\\\"pitch\\\":\\\"100\\\",\\\"pan\\\":\\\"0\\\"}\"]"}},
{"name":"BalloonFollower","status":true,"description":"Allow to show balloon icon on followers.","parameters":{}}
];
